# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image: devwithlando/gitpod-source:1-edge

tasks:
  - name:  Setup Gitpod for Lando
    command: |
      lando init --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components 1" --recipe drupal9 --webroot . --name lando-drupal9
      lando start
      lando composer require drush/drush
      lando composer install
      chmod ug+w -R /workspace/gitpod/sites/default/
      lando drush si -y --account-pass=admin --site-name='lando_drupal9' --db-url=mysql://drupal9:drupal9@database/drupal9 demo_umami
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))
  
ports:
  - port: 3306
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - marcostazi.VS-code-drupal
