# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install
    init: |
      cp -f config.yml ~/.lando/config.yml
      echo false > ~/.lando/cache/report_errors
      lando init --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components 1" --recipe drupal9 --webroot . --name lando-drupal9
      lando --clear
      lando start
      lando composer require drush/drush
      lando composer install
      chmod ug+w -R /workspace/gitpod/sites/default/
      echo -e "\n\$databases['default']['default'] = [\n'database' => 'drupal9',\n'username' => 'drupal9',\n'password' => 'drupal9',\n'host' => 'database',\n'port' => '3306',\n'driver' => 'mysql'\n];" >> /workspace/gitpod/sites/default/settings.php
      lando drush si -y --account-pass=admin --site-name='lando_drupal9' demo_umami
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))
  
ports:
  - port: 3306
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 4443
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true