# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install
    before: |
      cp -f config.yml ~/.lando/config.yml
      echo false > ~/.lando/cache/report_errors
    init: |
      lando init --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components 1" --recipe drupal9 --webroot . --name lando-drupal9
    command: |
      lando --clear
      lando start
      lando composer require drush/drush
      lando composer install
      chmod ug+w -R /workspace/gitpod/sites/default/
      cp /workspace/gitpod/sites/default/default.settings.php /workspace/gitpod/sites/default/settings.php
      echo -e "\n\$databases['default']['default'] = [\n'database' => 'drupal9',\n'username' => 'drupal9',\n'password' => 'drupal9',\n'host' => 'database',\n'port' => '3306',\n'driver' => 'mysql'\n];" >> /workspace/gitpod/sites/default/settings.php
      lando drush si -y --account-pass=admin --site-name='lando_drupal9' demo_umami
      gp preview $(gp url $(lando info --format=json | jq -r ".[0].urls[1]" | sed -e 's#http://localhost:\(\)#\1#'))
  
ports:
  - port: 3306
    onOpen: ignore
  - port: 80
    onOpen: ignore
  - port: 443
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 4443
    onOpen: ignore

github:
  prebuilds:
    master: true
    branches: false
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true

vscode:
  extensions:
    - felixfbecker.php-debug
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - EditorConfig.EditorConfig
    - esbenp.prettier-vscode
    - stylelint.vscode-stylelint
    - tombonnike.vscode-status-bar-format-toggle
    - usernamehw.errorlens
    - mblode.twig-language
    - marcostazi.VS-code-drupal