# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Drupal start
    init: |
      lando init --source remote --remote-url https://www.drupal.org/download-latest/tar.gz --remote-options="--strip-components 1" --recipe drupal9 --webroot . --name lando-drupal9
      lando start
      lando composer require drush/drush
      lando composer install
      gp await-port 8080 && gp preview $(gp url 8080)
  
ports:
  # db port
  - port: 3306
    onOpen: ignore
  - port: 8080
    onOpen: ignore
  - port: 8443
    onOpen: ignore
  - port: 9999
    onOpen: open-browser
    
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true