name: Automatic Stable Gitpod Image Update
on:
  schedule:
    - cron: '14 3 * * *'

jobs:
  auto-update-stable-images:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PIROG_TOKEN }}
          fetch-depth: 0
      - name: Setup git user
        shell: bash
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit and push
        shell: bash
        run: |
          git add .
          git commit --allow-empty -m "Triggering build to update stable images"
          git push origin main
